"""Compare generic region probes from two isolated TVM checkouts."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np

from forkcert.relational_oracle import compute_endpoint_oracle


def _contract_key(row):
    contract = row["contract"]
    return json.dumps(contract, sort_keys=True, separators=(",", ":"))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--buggy", required=True)
    parser.add_argument("--fixed", required=True)
    parser.add_argument("--out", required=True)
    args = parser.parse_args()
    buggy = json.loads(Path(args.buggy).read_text())
    fixed = json.loads(Path(args.fixed).read_text())
    if buggy["case_id"] != fixed["case_id"]:
        raise SystemExit("probe reports have different case IDs")
    if buggy["input_artifact_sha256"] != fixed["input_artifact_sha256"]:
        raise SystemExit("probe reports do not use the same input artifact")
    left = {row["region_id"]: row for row in buggy["regions"] if row["status"] == "REPLAYED"}
    right = {row["region_id"]: row for row in fixed["regions"] if row["status"] == "REPLAYED"}
    # Symbol names may be regenerated by legalization (e.g. ``take`` versus
    # ``take1``).  Pair only unique, identical ABI contracts; never infer a
    # relation from an operator name.
    left_by_contract: dict[str, list[dict]] = {}
    right_by_contract: dict[str, list[dict]] = {}
    for row in left.values():
        left_by_contract.setdefault(_contract_key(row), []).append(row)
    for row in right.values():
        right_by_contract.setdefault(_contract_key(row), []).append(row)
    rows = []
    for contract_key in sorted(set(left_by_contract) & set(right_by_contract)):
        candidates_a, candidates_b = left_by_contract[contract_key], right_by_contract[contract_key]
        if len(candidates_a) != 1 or len(candidates_b) != 1:
            rows.append({"status": "AMBIGUOUS_ABI_MAPPING", "buggy_regions": [r["region_id"] for r in candidates_a], "fixed_regions": [r["region_id"] for r in candidates_b]})
            continue
        a, b = candidates_a[0], candidates_b[0]
        output_a = np.load(a["artifact"])
        output_b = np.load(b["artifact"])
        oracle = compute_endpoint_oracle(output_a, output_b)
        rows.append({
            "buggy_region_id": a["region_id"],
            "fixed_region_id": b["region_id"],
            "status": "COMPARED",
            "same_input_contract": True,
            "buggy_repeat_exact": a["repeat_exact"],
            "fixed_repeat_exact": b["repeat_exact"],
            "cross_version_oracle": oracle.as_dict(),
            "runtime_variability": {
                "buggy": a.get("repeatability", {"status": "UNRECORDED"}),
                "fixed": b.get("repeatability", {"status": "UNRECORDED"}),
            },
        })
    stable_rows = [
        row for row in rows
        if row.get("status") == "COMPARED"
        and row["cross_version_oracle"].get("finite_match", False)
        and row["buggy_repeat_exact"]
        and row["fixed_repeat_exact"]
    ]
    compared_rows = [row for row in rows if row.get("status") == "COMPARED"]
    if stable_rows:
        claim = "CROSS_VERSION_LOCAL_REPLAY_ONLY"
    elif compared_rows:
        claim = "CROSS_VERSION_LOCAL_REPLAY_UNSTABLE"
    else:
        claim = "NO_COMMON_REPLAYABLE_REGION"
    report = {
        "schema_version": "forkcert.generic-tvm-region-probe-comparison.v0.1",
        "case_id": buggy["case_id"],
        "inputs": {"buggy": args.buggy, "fixed": args.fixed, "same_input_artifact": True},
        "regions": rows,
        "claim": claim,
        "limitations": [
            "buggy/fixed is an implementation comparison, not a mathematical truth oracle",
            "isolated symbol replay is not fixed-suffix mediation",
            "context changes between compiler versions are not invariant",
            "a local output discrepancy does not identify a unique compiler source",
        ],
    }
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n")
    print(json.dumps({"out": str(out), "claim": report["claim"], "regions": [row.get("buggy_region_id", row.get("status")) for row in rows]}, sort_keys=True))


if __name__ == "__main__":
    main()
