#!/usr/bin/env python3
"""Register compact next-round controls in the final-result manifest."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def main() -> None:
    manifest_path = ROOT / "results/final/manifest.json"
    manifest = json.loads(manifest_path.read_text())
    names = (
        "flash_control.json",
        "implementation_atlas.json",
        "implementation_atlas_seq128.json",
        "implementation_atlas_seq256.json",
        "natural_bank.json",
        "checkpoint_matrix.json",
        "checkpoint_carrier.json",
        "checkpoint_inductor.json",
        "implementation_matrix.json",
        "dtype_dynamic_boundary.json",
        "dtype_topology_fp32_seq64.json",
        "dtype_topology_fp32_seq128.json",
        "dtype_topology_fp32_seq256.json",
        "dtype_topology_tf32_seq64.json",
        "dtype_topology_tf32_seq128.json",
        "dtype_topology_tf32_seq256.json",
        "dtype_mapping_fp32_seq64.json",
        "dtype_mapping_fp32_seq128.json",
        "dtype_mapping_fp32_seq256.json",
        "dtype_mapping_fp32_seq64_full.json",
        "dtype_mapping_tf32_seq64.json",
        "dtype_mapping_tf32_seq128.json",
        "dtype_mapping_tf32_seq256.json",
        "dtype_semantic_fp32_seq64.json",
        "dtype_semantic_fp32_seq128.json",
        "dtype_semantic_fp32_seq256.json",
        "dtype_endpoint_mapping_fp32_seq128.json",
        "dtype_evolving_fp32_seq128_expanded.json",
        "dtype_evolving_fp32_seq64_full.json",
        "source_mapping_progress.json",
        "source_replay_gate.json",
        "source_matrix_static.json",
        "source_replay_schedule.json",
        "source_replay_matrix.json",
        "missing_case_diagnosis.json",
        "source_phase_audit.json",
        "matrix_cross_product_audit.json",
        "gpu_preflight.json",
        "gpu_preflight_external.json",
        "objective_audit.json",
        "cleanup.json",
        "aot_carrier_graph.json.gz",
        "carrier_census.json",
        "priority_carrier_chains.json",
        "priority_carrier_replay.json",
        "search_conclusion.json",
        "source_mapping_fp32_seq64_static.json",
        "source_mapping_fp32_seq128_static.json",
        "source_mapping_fp32_seq256_static.json",
        "source_mapping_tf32_seq64_static.json",
        "source_mapping_tf32_seq128_static.json",
        "source_mapping_tf32_seq256_static.json",
        "priority_carrier_chains.json",
        "dtype_semantic_tf32_seq64.json",
        "dtype_semantic_tf32_seq128.json",
        "dtype_semantic_tf32_seq256.json",
        "dtype_unresolved_boundary.json",
        "completion_audit.json",
        "region_intervention_pilot.json",
        "region_intervention_batch.json",
        "invocation_atlas.json",
        "checkpoint_matrix_shapes.json",
        "checkpoint_carrier_seq64.json",
        "checkpoint_carrier_seq256.json",
        "checkpoint_matrix_seq64.json",
        "checkpoint_matrix_seq256.json",
        "checkpoint_inductor_bf16_seq64.json",
        "checkpoint_inductor_bf16_seq256.json",
        "checkpoint_inductor_fp16.json",
        "checkpoint_inductor_fp16_seq64.json",
        "checkpoint_inductor_fp16_seq256.json",
        "checkpoint_inductor_fp32.json",
        "checkpoint_inductor_fp32_seq64.json",
        "checkpoint_inductor_fp32_seq256.json",
        "checkpoint_inductor_tf32.json",
        "checkpoint_inductor_tf32_seq64.json",
        "checkpoint_inductor_tf32_seq256.json",
        "evolving_triton_seq64.json",
        "evolving_triton_seq128.json",
        "evolving_triton_seq256.json",
        "evolving_triton_fp16_seq64.json",
        "evolving_triton_fp16_seq128.json",
        "evolving_triton_fp16_seq256.json",
        "long_horizon_bank.json",
        "long_horizon_trigger.json",
        "structured_carrier_trigger.json",
        "structured_carrier_confirmation.json",
        "seq1024_pilot.json",
        "backend_stage_diagnosis.json",
        "inductor_config_ablation.json",
        "inductor_config_heldout.json",
        "seq1024_query_campaign.json",
        "seq1024_reduction_campaign.json",
        "long_trigger_q_backward.json",
        "long_trigger_k_backward.json",
        "long_trigger_q_sum.json",
        "long_trigger_k_sum.json",
        "long_trigger_forward_joint.json",
        "l23_go_step64.json",
        "l23_go_step256.json",
        "l23_go_step1024.json",
        "l23_go_step2048.json",
        "l23_go_step4096.json",
        "l23_go_summary.json",
        "l23_attention_live_weight.json",
    )
    decomposition_prefixes = (
        "l23_go_path",
        "l23_residual_l24", "l23_go_l24",
        "l23_residual_l25", "l23_go_l25",
        "l23_residual_l26", "l23_go_l26",
        "l23_residual_l27", "l23_go_l27",
        "l23_terminal", "l23_final_norm",
    )
    names += tuple(
        name
        for prefix in decomposition_prefixes
        for name in (
            *(f"{prefix}_step{step}.json" for step in (64, 256, 1024, 2048, 4096)),
            f"{prefix}_summary.json",
        )
    )
    for name in names:
        path = ROOT / "results/final" / name
        data = path.read_bytes()
        manifest.setdefault("files", {})[name] = {
            "bytes": len(data),
            "sha256": hashlib.sha256(data).hexdigest(),
        }
    summary = ROOT / "results/final/summary.json"
    manifest["summary"] = {
        "bytes": summary.stat().st_size,
        "sha256": hashlib.sha256(summary.read_bytes()).hexdigest(),
    }
    manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n")
    print(json.dumps({"registered": [
        "flash_control.json", "implementation_atlas.json",
        "implementation_atlas_seq128.json", "implementation_atlas_seq256.json",
        "natural_bank.json",
        "checkpoint_matrix.json", "checkpoint_carrier.json",
        "checkpoint_inductor.json", "implementation_matrix.json",
        "invocation_atlas.json",
        "checkpoint_matrix_shapes.json", "checkpoint_carrier_seq64.json",
        "checkpoint_carrier_seq256.json", "checkpoint_matrix_seq64.json",
        "checkpoint_matrix_seq256.json", "checkpoint_inductor_bf16_seq64.json",
        "checkpoint_inductor_bf16_seq256.json", "checkpoint_inductor_fp16.json",
        "checkpoint_inductor_fp16_seq64.json", "checkpoint_inductor_fp16_seq256.json",
        "checkpoint_inductor_fp32.json", "checkpoint_inductor_fp32_seq64.json",
        "checkpoint_inductor_fp32_seq256.json", "checkpoint_inductor_tf32.json",
        "checkpoint_inductor_tf32_seq64.json", "checkpoint_inductor_tf32_seq256.json",
        "evolving_triton_seq64.json", "evolving_triton_seq128.json",
        "evolving_triton_seq256.json",
        "evolving_triton_fp16_seq64.json",
        "evolving_triton_fp16_seq128.json",
        "evolving_triton_fp16_seq256.json",
        "structured_carrier_trigger.json",
        "structured_carrier_confirmation.json",
        "dtype_dynamic_boundary.json",
        "dtype_topology_fp32_seq64.json",
        "dtype_topology_fp32_seq128.json",
        "dtype_topology_fp32_seq256.json",
        "dtype_topology_tf32_seq64.json",
        "dtype_topology_tf32_seq128.json",
        "dtype_topology_tf32_seq256.json",
        "dtype_mapping_fp32_seq64.json",
        "dtype_mapping_fp32_seq128.json",
        "dtype_mapping_fp32_seq256.json",
        "dtype_mapping_tf32_seq64.json",
        "dtype_mapping_tf32_seq128.json",
        "dtype_mapping_tf32_seq256.json",
        "dtype_semantic_fp32_seq64.json",
        "dtype_semantic_fp32_seq128.json",
        "dtype_semantic_fp32_seq256.json",
        "dtype_semantic_tf32_seq64.json",
        "dtype_semantic_tf32_seq128.json",
        "dtype_semantic_tf32_seq256.json",
        "dtype_unresolved_boundary.json",
        "completion_audit.json",
        "region_intervention_pilot.json",
        "region_intervention_batch.json",
        "source_mapping_progress.json",
        "source_replay_gate.json",
        "source_matrix_static.json",
        "source_replay_schedule.json",
        "source_replay_matrix.json",
        "missing_case_diagnosis.json",
        "source_phase_audit.json",
        "matrix_cross_product_audit.json",
        "gpu_preflight.json",
        "objective_audit.json",
        "cleanup.json",
        "aot_carrier_graph.json.gz",
        "carrier_census.json",
        "source_mapping_fp32_seq64_static.json",
        "source_mapping_fp32_seq128_static.json",
        "source_mapping_fp32_seq256_static.json",
        "source_mapping_tf32_seq64_static.json",
        "source_mapping_tf32_seq128_static.json",
        "source_mapping_tf32_seq256_static.json",
        "search_conclusion.json",
    ]}))


if __name__ == "__main__":
    main()
