#!/usr/bin/env python
from __future__ import annotations

import argparse
import json
import math
from pathlib import Path

from forkcert.report import CLAIM_SCOPE, markdown_table


def gamma(k: int, unit_roundoff: float) -> float:
    value = k * unit_roundoff
    if value >= 1.0:
        return math.inf
    return value / (1.0 - value)


def main() -> None:
    parser = argparse.ArgumentParser(description="Conditional large-vocabulary log-softmax path-difference bound.")
    parser.add_argument("--isolation", required=True)
    parser.add_argument("--delta", type=float, default=1e-6)
    parser.add_argument("--out", default="results/phase2_logsoftmax_bound.json")
    parser.add_argument("--report", default="reports/phase2_logsoftmax_bound.md")
    args = parser.parse_args()

    isolation = json.loads(Path(args.isolation).read_text(encoding="utf-8"))
    n = int(isolation["vocabulary_outputs"] // isolation["positions"])
    u = 2.0**-24
    reduction_gamma = gamma(n - 1, u)
    # CUDA 12.6 documents expf at 2 ULP. For positive normal float values,
    # one ULP is at most 2u relative to the exact value.
    exp_relative = 4.0 * u
    local_relative = (1.0 + reduction_gamma) * (1.0 + exp_relative) - 1.0
    if local_relative >= 1.0:
        deterministic_logsum_difference = math.inf
    else:
        deterministic_logsum_difference = math.log((1.0 + local_relative) / (1.0 - local_relative))
    max_logp = float(isolation["max_abs_fp32_logprob"])
    # One logf ULP and final FP32 subtraction on each path. The term is
    # deliberately conservative and data-dependent through the observed range.
    transcendental_and_output = 2.0 * u + 4.0 * u * max(1.0, max_logp)
    deterministic = deterministic_logsum_difference + transcendental_and_output

    lam = math.sqrt(2.0 * math.log(2.0 / args.delta))
    probability_reduction = lam * math.sqrt(n) * u
    probability_local = math.sqrt(probability_reduction**2 + exp_relative**2)
    probability_logsum_difference = math.sqrt(2.0) * probability_local
    probability = probability_logsum_difference + transcendental_and_output
    empirical_p99 = float(isolation["target_delta_p99"])
    empirical_max = float(isolation["target_delta_max"])

    result = {
        "schema_version": "forkcert.phase2.logsoftmax_bound.v1",
        "certificate_kind": "vendor_documented_conditional",
        "analytic_legal": False,
        "analytic_legal_blockers": [
            "CUDA 12.6 states expf/logf ULP figures are generated by non-exhaustive tests and are not guaranteed bounds.",
            "The installed binary kernel implementation is profiled but not source-level verified against every compiler/math-mode assumption.",
        ],
        "vocabulary_size": n,
        "fp32_unit_roundoff": u,
        "arbitrary_order_reduction_gamma": reduction_gamma,
        "vendor_expf_ulp": 2,
        "vendor_logf_ulp": 1,
        "vendor_doc": "https://docs.nvidia.com/cuda/archive/12.6.0/cuda-c-programming-guide/index.html#mathematical-functions",
        "vendor_contract_guaranteed": False,
        "probability_delta": args.delta,
        "higham_mary_lambda": lam,
        "deterministic_conditional_bound": deterministic,
        "probability_conditional_bound": probability,
        "empirical_target_delta_p99": empirical_p99,
        "empirical_target_delta_max": empirical_max,
        "deterministic_tightness_over_p99": deterministic / empirical_p99 if empirical_p99 else None,
        "probability_tightness_over_p99": probability / empirical_p99 if empirical_p99 else None,
        "empirical_within_deterministic_conditional": empirical_max <= deterministic,
        "classification_permission": "stable/unknown diagnostic only; prohibited for certified bug classification",
        "formula": (
            "B_det = log((1+rho)/(1-rho)) + transcendental/output terms, "
            "rho=(1+gamma_(n-1))*(1+4u)-1; arbitrary positive-sum order per path"
        ),
    }
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    keys = [
        "certificate_kind",
        "vocabulary_size",
        "deterministic_conditional_bound",
        "probability_conditional_bound",
        "empirical_target_delta_p99",
        "empirical_target_delta_max",
        "deterministic_tightness_over_p99",
        "probability_tightness_over_p99",
        "analytic_legal",
    ]
    report = "\n".join(
        [
            "# Phase 2 Log-Softmax Conditional Bound",
            "",
            "## Claim Scope",
            CLAIM_SCOPE,
            "",
            "## Confound Checklist",
            "- shared upstream logits: PASS",
            "- runtime input/accumulator/output kernel types profiled: PASS",
            "- arbitrary reduction order covered: PASS",
            "- CUDA expf/logf ULP values recorded: PASS",
            "- vendor values are guaranteed mathematical bounds: FAIL",
            "- certified bug classification enabled: FAIL / prohibited",
            "",
            "## Delta Self Control",
            "Both half-input and float-input log-softmax outputs are bitwise reproducible across the two measured calls.",
            "",
            "## Summary",
            markdown_table([{key: result[key] for key in keys}], keys),
            "",
            "## Legal Status",
            "This is a vendor-documented conditional envelope, not `analytic_legal`. CUDA 12.6 lists `expf` at 2 ULP and `logf` at 1 ULP, but explicitly says the table is based on extensive, non-exhaustive testing and is not guaranteed. Consequently this result may support conservative stable/unknown analysis but cannot prove that a larger delta is a bug.",
            "",
            "## Formula",
            result["formula"],
            "",
            "## External Validity",
            "The measured range and kernels are from CUDA 12.6 on Tesla T4 with FP16 autocast. Native BF16 uses different input types and requires a new isolation audit.",
            "",
        ]
    )
    Path(args.report).parent.mkdir(parents=True, exist_ok=True)
    Path(args.report).write_text(report, encoding="utf-8")
    print(json.dumps({key: result[key] for key in keys}, indent=2))


if __name__ == "__main__":
    main()
