#!/usr/bin/env python3
"""Frozen initialization confirmation, separate from development and bias tests.

Primary claim: probability(candidate loss > reference loss) > 1/2 at the fixed
endpoint, conditional on this tokenizer, model and data order. No minimum
engineering benefit, mean-loss guarantee or persistent-bias claim is implied.
"""
import argparse
import json
import math
import os
from pathlib import Path
import subprocess
import sys

import numpy as np
import torch
from scripts import run_liger_language_pilot as pilot
from scripts.run_liger_language_followup import OUT as DEVELOPMENT
from scripts.run_liger_single_boundary_collapse import file_sha256
from scripts.run_training_numerical_v2 import BASE, ROOT, save_new

OUT = BASE / "language_training_confirmation_iid"
N = 16


def tail(count, probability=0.5):
    return sum(math.comb(N, k) * probability**k * (1 - probability)**(N-k) for k in range(count, N+1))


def freeze():
    development = json.loads((DEVELOPMENT / "summary.json").read_text())
    if development["status"] != "COMPLETE_FIXED_PAIRED_DEVELOPMENT_RUN_SET":
        raise SystemExit("Development set is incomplete")
    seeds = np.random.default_rng(2026090601).integers(0, 2**31 - 1, size=N).tolist()
    critical = next(k for k in range(N+1) if tail(k) <= 0.05)
    save_new(OUT / "plan.json", {
        "status": "FROZEN_BEFORE_CONFIRMATION_RESULTS", "pairs": N,
        "seed_sampling": "IID_WITH_REPLACEMENT_NO_DUPLICATE_FILTERING",
        "supersedes_unexecuted_plan": "language_training_confirmation/plan.json used sampling without replacement; corrected before any confirmation execution to match the binomial model",
        "initialization_seeds": seeds, "steps": 1024, "alpha": 0.05,
        "primary_endpoint": "Common FP32 evaluation loss at step 1024",
        "direction_frozen_from_development": "CANDIDATE_MINUS_REFERENCE_POSITIVE",
        "null": "Probability(candidate loss > reference loss) <= 0.5",
        "inference": "Exact one-sided binomial sign test; ties count as nonpositive",
        "independent_unit": "One paired initialization, with common fixed data order",
        "assumptions": "Independent initializations generated by the declared PRNG design; unchanged execution and evaluation protocol. No independence of training steps is assumed.",
        "minimum_positive_pairs_for_rejection": critical,
        "power_at_positive_pair_probability_0_8": tail(critical, 0.8),
        "power_design_note": "0.8 is a planning alternative, not an estimate established by four development pairs",
        "failed_or_nonfinite_run": "INCONCLUSIVE_ENTIRE_CONFIRMATION_NO_REPLACEMENT",
        "data_use": "NEW_INITIALIZATION_CONFIRMATION_NOT_NEW_IMPLEMENTATION",
        "no_early_stopping": True,
        "runner_sha256": file_sha256(Path(__file__)),
        "development_summary_sha256": file_sha256(DEVELOPMENT / "summary.json"),
        "scope": "Small four-layer language model, WikiText subset and fixed data/evaluation order; not full-size pretrained LLMs or material quality improvement",
    })
    original = json.loads((pilot.PILOT / "protocol.json").read_text())
    for pair, seed in enumerate(seeds):
        directory = OUT / f"pair{pair}"
        protocol = json.loads(json.dumps(original))
        protocol.update(steps=1024, eval_every=256, data_use="NEW_INITIALIZATION_CONFIRMATION",
                        purpose="Frozen primary paired-loss sign endpoint; shared execution runner")
        protocol["model"]["initialization_seed"] = seed
        save_new(directory / "protocol.json", protocol)
        for split in ("train", "validation"):
            (directory / f"{split}.npy").symlink_to((pilot.PILOT / f"{split}.npy").resolve())


def summarize():
    plan = json.loads((OUT / "plan.json").read_text())
    rows = []
    for pair in range(N):
        root = OUT / f"pair{pair}"
        paths = [root / c / "status.json" for c in ("candidate", "reference")]
        if not all(p.exists() for p in paths):
            raise SystemExit(f"Pair {pair} incomplete; do not test a partial set")
        c, r = [json.loads(p.read_text()) for p in paths]
        if any(p["status"] != "COMPLETE_DEVELOPMENT_PILOT" for p in (c, r)):
            raise SystemExit("Underlying execution failed; confirmation remains inconclusive")
        if c["initial_parameters_sha256"] != r["initial_parameters_sha256"]:
            raise RuntimeError("Initialization not matched")
        logs = [[json.loads(s) for s in (root / condition / "steps.jsonl").read_text().splitlines()]
                for condition in ("candidate", "reference")]
        if any(len(log) != plan["steps"] for log in logs) or any(x["offsets"] != y["offsets"] or x["step"] != y["step"] for x, y in zip(*logs)):
            raise RuntimeError("Training horizon or paired inputs not matched")
        if any(p["evaluations"][-1]["step"] != plan["steps"] for p in (c, r)):
            raise RuntimeError("Primary checkpoint missing")
        gap = c["evaluations"][-1]["shared_evaluation_loss"] - r["evaluations"][-1]["shared_evaluation_loss"]
        rows.append({"pair": pair, "candidate_minus_reference_loss": gap,
                     "candidate_status_sha256": file_sha256(paths[0]),
                     "reference_status_sha256": file_sha256(paths[1])})
    positives = sum(row["candidate_minus_reference_loss"] > 0 for row in rows)
    p_value = tail(positives)
    save_new(OUT / "summary.json", {
        "status": "COMPLETE_FROZEN_INITIALIZATION_CONFIRMATION",
        "plan_sha256": file_sha256(OUT / "plan.json"), "rows": rows,
        "positive_pairs": positives, "total_pairs": N, "p_value": p_value,
        "primary_prediction_confirmed": p_value <= plan["alpha"],
        "mean_loss_gap_descriptive_only": float(np.mean([r["candidate_minus_reference_loss"] for r in rows])),
        "persistent_bias": "NOT_PROVED_BY_THIS_TRAINING_ENDPOINT",
        "material_quality_benefit": "NOT_TESTED_NO_MATERIALITY_MARGIN",
        "scope": plan["scope"],
    })


def main():
    p = argparse.ArgumentParser()
    p.add_argument("command", choices=("freeze", "train", "queue", "summarize"))
    p.add_argument("--pairs", nargs="+", type=int, choices=range(N))
    p.add_argument("--pair", type=int, choices=range(N))
    p.add_argument("--condition", choices=("candidate", "reference"))
    p.add_argument("--device", default="cuda:0")
    args = p.parse_args()
    if args.command == "freeze":
        freeze(); return
    plan = json.loads((OUT / "plan.json").read_text())
    if plan["runner_sha256"] != file_sha256(Path(__file__)):
        raise SystemExit("Frozen confirmation driver changed")
    if args.command == "summarize":
        summarize(); return
    if args.command == "train":
        if args.pair is None or args.condition is None:
            p.error("train requires pair and condition")
        pilot.PILOT = OUT / f"pair{args.pair}"
        pilot.train(args.condition, torch.device(args.device))
        return
    if not args.pairs:
        p.error("queue requires pairs")
    for pair in args.pairs:
        for condition in ("candidate", "reference"):
            command = [sys.executable, str(Path(__file__)), "train", "--pair", str(pair),
                       "--condition", condition, "--device", args.device]
            root = OUT / f"pair{pair}"
            save_new(root / f"{condition}_execution_plan.json", {"command": command,
                     "cuda_visible_devices": os.environ.get("CUDA_VISIBLE_DEVICES")})
            with (root / f"{condition}.log").open("x") as log:
                result = subprocess.run(command, cwd=ROOT, stdout=log, stderr=subprocess.STDOUT)
            save_new(root / f"{condition}_execution_result.json", {"returncode": result.returncode})
            if result.returncode:
                raise SystemExit(result.returncode)


if __name__ == "__main__":
    main()
