#!/usr/bin/env python3
"""Step 6: negative controls and generalization of the automatic reference.

Three structures (stage summary section 11):

1. reduction with a deliberately omitted term: without a task specification
   f the defect is invisible (K_R follows the declared IR) and the report says
   the task semantics was not checked; with the source computation supplied as
   f, K_R - f exposes it;
2. exp -> sum -> divide written three ways: each reference is generated by the
   same evaluator without a dedicated reference; recompositions with the same
   real semantics give overlapping references, the exp2 rewrite with a rounded
   log2(e) constant shows up as a declared-semantics difference (term 4);
3. compute -> store -> load -> compute: the reference keeps the upstream
   difference through the load; pinning the load to its captured value
   downgrades the output to a conditional local reference.

    python scripts/run_step6_negative_controls.py --out results/reference_eval/step6_negative_controls.json
"""

from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT))

import torch  # noqa: E402

from kernel_analyzer.reference_eval import intervals as iv  # noqa: E402
from kernel_analyzer.reference_eval.capture import TritonLaunchRecorder  # noqa: E402
from kernel_analyzer.reference_eval.ttir_eval import KernelReferenceEvaluator  # noqa: E402
from kernel_analyzer.reference_eval.ttir_parser import parse_ttir  # noqa: E402
from scripts import reference_eval_kernels as k  # noqa: E402


def capture(fn):
    recorder = TritonLaunchRecorder()
    with recorder:
        fn()
        torch.cuda.synchronize()
    return recorder.launches[-1]


def evaluate(launch, **kwargs):
    t0 = time.time()
    result = KernelReferenceEvaluator(parse_ttir(launch.asm["ttir"])).evaluate(launch, **kwargs)
    return result, time.time() - t0


def output(result, name):
    for ident, buf in result.buffers.items():
        if buf.name == name:
            m = buf.written
            return buf.actual_after[m], buf.lo[m], buf.hi[m], buf.st[m], buf.cond[m]
    raise KeyError(name)


def interval_sign(lo, hi):
    return {"positive": int((lo > 0).sum()), "negative": int((hi < 0).sum()),
            "contains_zero": int(((lo <= 0) & (hi >= 0)).sum())}


def residual(actual, lo, hi):
    return iv.add_bounds(actual, -hi)[0], iv.add_bounds(actual, -lo)[1]


def difference(alo, ahi, blo, bhi):
    return iv.add_bounds(alo, -bhi)[0], iv.add_bounds(ahi, -blo)[1]


def structure_reduction():
    rows, n = 64, 300
    x = torch.randn(rows, n, device="cuda")
    cand = capture(lambda: k.row_sum_drops_last[(rows,)](x, torch.empty(rows, device="cuda"), n, BLOCK=512))
    spec = capture(lambda: k.row_sum[(rows,)](x, torch.empty(rows, device="cuda"), n, BLOCK=512))
    rc, sec_c = evaluate(cand)
    rs, sec_s = evaluate(spec)
    act, lo, hi, st, cond = output(rc, "Y")
    _, flo, fhi, _, _ = output(rs, "Y")
    num_lo, num_hi = residual(act, lo, hi)
    sem_lo, sem_hi = difference(lo, hi, flo, fhi)
    x_last = x[:, -1].double().cpu().numpy()
    return {
        "candidate": "row_sum_drops_last", "specification": "row_sum (source computation)",
        "without_specification": {
            "task_semantics": "not checked (f taken as the declared semantics of the candidate IR)",
            "numerical_residual_K_minus_KR": interval_sign(num_lo, num_hi),
            "max_abs_numerical_residual": float(np.max(np.maximum(np.abs(num_lo), np.abs(num_hi)))),
            "defect_visible": False,
        },
        "with_specification": {
            "semantic_term_KR_minus_f": interval_sign(sem_lo, sem_hi),
            "semantic_term_equals_minus_last_element": bool(((sem_lo <= -x_last) & (-x_last <= sem_hi)).all()),
            "max_abs_semantic_term": float(np.max(np.maximum(np.abs(sem_lo), np.abs(sem_hi)))),
            "defect_detected_rows": int(((sem_lo > 0) | (sem_hi < 0)).sum()),
            "rows": rows,
        },
        "seconds": round(sec_c + sec_s, 3),
    }


def structure_recomposition():
    n = 1000
    x = torch.randn(n, device="cuda") * 3.0
    variants = {"exp": k.softmax_exp, "exp2_with_rounded_log2e": k.softmax_exp2, "reciprocal": k.softmax_reciprocal}
    refs, report = {}, {}
    for name, kernel in variants.items():
        launch = capture(lambda kernel=kernel: kernel[(1,)](x, torch.empty_like(x), n, BLOCK=1024))
        result, seconds = evaluate(launch)
        act, lo, hi, st, cond = output(result, "Y")
        r_lo, r_hi = residual(act, lo, hi)
        refs[name] = (lo, hi)
        report[name] = {
            "classes_complete": int(((st == 0) & ~cond).sum()), "elements": int(st.size),
            "reference_width_max": float(np.max(hi - lo)),
            "relative_width_max": float(np.max((hi - lo) / np.maximum(np.abs(lo), 1e-300))),
            "numerical_residual_K_minus_KR": interval_sign(r_lo, r_hi),
            "max_abs_numerical_residual": float(np.max(np.maximum(np.abs(r_lo), np.abs(r_hi)))),
            "dedicated_reference_code": False, "seconds": round(seconds, 3),
        }
    base = refs["exp"]
    comparisons = {}
    for name in ("exp2_with_rounded_log2e", "reciprocal"):
        d_lo, d_hi = difference(*refs[name], *base)
        comparisons[f"{name}_minus_exp"] = {
            **interval_sign(d_lo, d_hi),
            "max_abs_difference": float(np.max(np.maximum(np.abs(d_lo), np.abs(d_hi)))),
        }
    return {"variants": report, "declared_semantics_differences": comparisons}


def structure_store_load():
    n = 1000
    x = torch.randn(n, device="cuda")
    launch = capture(lambda: k.store_load_chain[(4,)](x, torch.empty_like(x), torch.empty_like(x), n, BLOCK=256))
    out = {}
    for label, pins in (("composed", ()), ("load_pinned_to_capture", ("%u",))):
        result, seconds = evaluate(launch, pin_loads=pins)
        act, lo, hi, st, cond = output(result, "Y")
        r_lo, r_hi = residual(act, lo, hi)
        out[label] = {
            "classes": {"complete_composed": int(((st == 0) & ~cond).sum()),
                        "conditional_local": int(((st == 0) & cond).sum()),
                        "not_established": int((st >= 4).sum())},
            "residual": interval_sign(r_lo, r_hi), "seconds": round(seconds, 3),
        }
    return out


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args()
    torch.manual_seed(20261002)
    report = {
        "schema": "kernel-analyzer-step6-negative-controls-v1",
        "reference_mode": "numerical_difference",
        "triton": __import__("triton").__version__,
        "reduction_with_omitted_term": structure_reduction(),
        "exp_sum_divide_recompositions": structure_recomposition(),
        "compute_store_load_compute": structure_store_load(),
    }
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(report, indent=2) + "\n")
    print(json.dumps(report, indent=2))


if __name__ == "__main__":
    main()
