"""Automated, deterministic forward/backward numerical-bias analysis."""

from .api import (
    AnalysisReport,
    AnalysisSpec,
    AnalysisState,
    CandidateBackend,
    CaseCertificate,
    ConcreteFBProof,
    ReferenceProvider,
    ResourceBudget,
    StepExecution,
    TierEvidence,
)
from .runner import Analyzer
from .semantics import SemanticRegistry, SemanticRule
from .property import (
    SignedTransportState,
    derive_signed_rounding_error,
    signed_event_transport,
    signed_transport_certificate,
)
from .seup import (
    FrozenCarrier,
    SEUPCalibrator,
    SEUPAccumulator,
    SymmetricSEUPEvaluator,
    adamw_update,
    adamw_effective_update_delta,
    alternating_sign_schedule,
    balanced_sign_schedule,
    force_carrier_sign,
    flip_carrier_component,
    sgd_effective_update_delta,
)
from .geometry import (
    GeometryAnalyzer,
    load_spool,
    normalized_gram,
    projected_persistence,
    subspace_overlap,
)
from .bias import (
    BiasLayer,
    BiasProperty,
    BiasStatus,
    BiasTrace,
    BiasTracePolicy,
    LayerCertificate,
    LayerValue,
    PropertyDecision,
)
from .bias_formation import (
    BiasFormationTrace,
    FormationLayer,
    FormationPolicy,
    FormationStatus,
    ProjectionCertificate,
    VectorObservation,
    summarize_vectors,
)
from .bias_consequence import BiasConsequenceTrace, ConsequenceStatus, ConsequenceValue
from .bias_predictor import ReferenceOnlyInputs, ReferenceOnlyPredictor, validate_reference_payload
from .bias_formation_v21 import (
    BiasFormationTrace as BiasFormationTraceV21,
    CommonStateCertificate,
    FormationLayer as FormationLayerV21,
    FormationPolicy as FormationPolicyV21,
    FormationStatus as FormationStatusV21,
    LayerPopulationCertificate,
    StateVectorObservation,
    summarize_state_vectors,
    summarize_streamed_state_vectors,
)
from .bias_consequence_v21 import (
    BiasConsequenceTrace as BiasConsequenceTraceV21,
    ConsequenceStatus as ConsequenceStatusV21,
    UpdateValue,
)
from .bias_formation_v22 import (
    BiasLevel,
    BiasV22Status,
    ConditionalPolicy,
    TrajectoryPolicy,
    summarize_conditional_vectors,
    summarize_conditional_gram,
    aggregate_conditional_debias,
    certify_trajectory_separation,
    classify_global_certificate,
)
from .bias_oracle_recovery import (
    BiasRiskCertificate,
    RecoveryDisposition,
    RecoveryPrediction,
    compare_recovery,
    combine_risk_witnesses,
    missing_screen_prediction,
    predict_conditional_source_risk,
    predict_crossfit_projection_risk,
    predict_population_coherence_risk,
    predict_reference_relative_risk,
    predict_response_rectification_risk,
    predict_source_fidelity_boundary,
)
from .joint_event_oracle import (
    JointEventCertificate,
    certify_joint_event_gram,
    gram_from_event_vectors,
)
from .reference_relative_oracle import (
    ReferenceRelativeCertificate,
    ReferenceRelativeObservation,
    certify_reference_relative,
)
from .tcmp_campaign import (
    ModelCampaignSpec,
    ModelCellSpec,
    TCMPDisposition,
    audit_denominator,
    benjamini_hochberg,
    exact_sign_flip_statistics,
    holm_rejections,
)

__all__ = [
    "AnalysisReport",
    "AnalysisSpec",
    "AnalysisState",
    "Analyzer",
    "CandidateBackend",
    "CaseCertificate",
    "ConcreteFBProof",
    "ReferenceProvider",
    "ResourceBudget",
    "SemanticRegistry",
    "SemanticRule",
    "SEUPAccumulator",
    "SEUPCalibrator",
    "FrozenCarrier",
    "SymmetricSEUPEvaluator",
    "SignedTransportState",
    "StepExecution",
    "TierEvidence",
    "ModelCampaignSpec",
    "ModelCellSpec",
    "TCMPDisposition",
    "audit_denominator",
    "benjamini_hochberg",
    "exact_sign_flip_statistics",
    "holm_rejections",
    "derive_signed_rounding_error",
    "signed_event_transport",
    "signed_transport_certificate",
    "adamw_effective_update_delta",
    "adamw_update",
    "alternating_sign_schedule",
    "balanced_sign_schedule",
    "force_carrier_sign",
    "flip_carrier_component",
    "sgd_effective_update_delta",
    "GeometryAnalyzer",
    "load_spool",
    "normalized_gram",
    "projected_persistence",
    "subspace_overlap",
    "BiasLayer",
    "BiasProperty",
    "BiasStatus",
    "BiasTrace",
    "BiasTracePolicy",
    "LayerCertificate",
    "LayerValue",
    "PropertyDecision",
    "BiasFormationTrace",
    "FormationLayer",
    "FormationPolicy",
    "FormationStatus",
    "ProjectionCertificate",
    "VectorObservation",
    "summarize_vectors",
    "BiasConsequenceTrace",
    "ConsequenceStatus",
    "ConsequenceValue",
    "ReferenceOnlyInputs",
    "ReferenceOnlyPredictor",
    "validate_reference_payload",
    "BiasFormationTraceV21",
    "CommonStateCertificate",
    "FormationLayerV21",
    "FormationPolicyV21",
    "FormationStatusV21",
    "LayerPopulationCertificate",
    "StateVectorObservation",
    "summarize_state_vectors",
    "summarize_streamed_state_vectors",
    "BiasConsequenceTraceV21",
    "ConsequenceStatusV21",
    "UpdateValue",
    "BiasLevel",
    "BiasV22Status",
    "ConditionalPolicy",
    "TrajectoryPolicy",
    "summarize_conditional_vectors",
    "summarize_conditional_gram",
    "aggregate_conditional_debias",
    "certify_trajectory_separation",
    "classify_global_certificate",
    "RecoveryDisposition",
    "RecoveryPrediction",
    "BiasRiskCertificate",
    "compare_recovery",
    "combine_risk_witnesses",
    "missing_screen_prediction",
    "predict_conditional_source_risk",
    "predict_crossfit_projection_risk",
    "predict_population_coherence_risk",
    "predict_reference_relative_risk",
    "predict_response_rectification_risk",
    "predict_source_fidelity_boundary",
    "JointEventCertificate",
    "certify_joint_event_gram",
    "gram_from_event_vectors",
    "ReferenceRelativeCertificate",
    "ReferenceRelativeObservation",
    "certify_reference_relative",
]
